version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.6
    - 8.2.7
    - 8.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.5
    - 6.2.7
  - dependency-name: react-overlays
    versions:
    - 4.1.1
    - 5.0.0
  - dependency-name: marked
    versions:
    - 0.7.0
    - 2.0.0
    - 2.0.1
  - dependency-name: markdown-to-jsx
    versions:
    - 6.11.4
    - 7.1.1
  - dependency-name: tar
    versions:
    - 2.2.2
    - 6.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: bootstrap
    versions:
    - 4.1.2
  - dependency-name: prop-types
    versions:
    - 15.7.2
  - dependency-name: lodash-es
    versions:
    - 4.17.14
  - dependency-name: node-sass
    versions:
    - 4.13.1
  - dependency-name: babel-eslint
    versions:
    - 10.1.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.1.11
  - dependency-name: lodash.template
    versions:
    - 4.5.0
  - dependency-name: lodash.mergewith
    versions:
    - 4.6.2
  - dependency-name: fstream
    versions:
    - 1.0.12
